#!/usr/bin/env python3
"""
Convert the AP Cybersecurity standards spreadsheet (exported CSV) into
curriculum/frameworks/ap-cybersecurity/standards.yaml.

Source columns: Standard, Description, parent, cleaned_description, dict
  - `Description` is used (YAML handles the original double quotes fine).
  - `cleaned_description` and `dict` are derived columns and are ignored.

The ID shape encodes the level:
  "1"        unit
  "1.1"      topic
  "1.1.A"    learning_objective   (the assessable level)
  "1.1.A.1"  essential_knowledge  (zoom-in reference; not graded directly)

Units 3-5 and their topics are missing from the source sheet. They are
filled in here as DRAFT records (status: draft) with titles inferred from
their learning objectives, so the tree is complete. Replace them with the
official titles and mark them `status: official`.

Usage:  python tools/csv_to_yaml.py
"""
import csv
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data/source/ap-cybersecurity-ced.csv"
OUT = ROOT / "curriculum/frameworks/ap-cybersecurity/standards.yaml"

LEVELS = {0: "unit", 1: "topic", 2: "learning_objective", 3: "essential_knowledge"}

# First word of a learning objective -> what kind of evidence it demands.
# Kept in sync with `demands` in framework.yaml.
VERB_DEMAND = {
    "identify": "recognize",
    "describe": "recognize",
    "explain": "explain",
    "determine": "decide",
    "assess": "decide",
    "evaluate": "decide",
    "configure": "perform",
    "apply": "perform",
}

# Missing from the sheet. Titles inferred from the learning objectives beneath them.
DRAFTS = {
    "3": "Network Security",
    "3.1": "Network Attacks & Vulnerabilities",
    "3.2": "Network Managerial Controls & Wireless Security",
    "3.3": "Network Segmentation",
    "3.4": "Network Firewalls",
    "3.5": "Detecting Network Attacks",
    "4": "Device Security",
    "4.1": "Device Vulnerabilities & Malware",
    "4.2": "Authentication & Password Security",
    "4.3": "Device Hardening Controls",
    "4.4": "Detecting Device Attacks",
    "5": "Application & Data Security",
    "5.1": "Application & Data Vulnerabilities",
    "5.2": "Data Classification & Access Control",
    "5.3": "Symmetric Encryption",
    "5.4": "Asymmetric Encryption",
    "5.5": "Secure Application Design",
    "5.6": "Detecting Attacks on Applications & Data",
}


class QuotedId(str):
    """Always emit IDs double-quoted so "1.1" never becomes a float in other YAML parsers."""


yaml.SafeDumper.add_representer(
    QuotedId, lambda d, v: d.represent_scalar("tag:yaml.org,2002:str", v, style='"')
)


def level_of(sid: str) -> str:
    return LEVELS[sid.count(".")]


def parent_of(sid: str):
    return sid.rsplit(".", 1)[0] if "." in sid else None


def sort_key(sid: str):
    # "1.10.B.2" sorts numerically/alphabetically per segment
    return [int(p) if p.isdigit() else p for p in sid.split(".")]


def main():
    rows = {}
    with SRC.open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            sid = r["Standard"].strip()
            desc = re.sub(r"\s+", " ", r["Description"]).strip()
            parent = r["parent"].strip()
            parent = None if parent in ("", "null") else parent
            assert parent == parent_of(sid), f"parent mismatch on {sid}"
            rows[sid] = desc

    records = []
    all_ids = set(rows) | set(DRAFTS)
    for sid in sorted(all_ids, key=sort_key):
        lvl = level_of(sid)
        rec = {"id": QuotedId(sid), "level": lvl}
        if parent_of(sid):
            rec["parent"] = QuotedId(parent_of(sid))

        if sid in rows:
            desc = rows[sid]
            if lvl in ("unit", "topic") and " | " in desc:
                title, summary = desc.split(" | ", 1)
                rec["title"] = title.strip()
                rec["summary"] = summary.strip()
            else:
                rec["text"] = desc
            rec["status"] = "official" if lvl in ("learning_objective", "essential_knowledge") else "paraphrase"
        else:
            rec["title"] = DRAFTS[sid]
            rec["status"] = "draft"

        if lvl == "learning_objective":
            verb = rec["text"].split()[0].lower()
            rec["verb"] = verb
            rec["demand"] = VERB_DEMAND.get(verb, "unknown")

        records.append(rec)

    # Sanity: every parent exists
    ids = {r["id"] for r in records}
    missing = sorted({r["parent"] for r in records if "parent" in r and r["parent"] not in ids})
    assert not missing, f"missing parents: {missing}"

    header = (
        "# yaml-language-server: $schema=../../../schema/standards.schema.json\n"
        "# AP Cybersecurity standards — GENERATED by tools/csv_to_yaml.py. Do not hand-edit;\n"
        "# edit data/source/ap-cybersecurity-ced.csv (or the DRAFTS table) and regenerate.\n"
        "#\n"
        "# status: official   = text from the Course and Exam Description\n"
        "#         paraphrase = teacher-written summary of a unit/topic\n"
        "#         draft      = placeholder inferred from child objectives; needs the official title\n\n"
    )
    counts = {}
    for r in records:
        counts[r["level"]] = counts.get(r["level"], 0) + 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(
            {"framework": "ap-cybersecurity", "standards": records},
            f, sort_keys=False, allow_unicode=True, width=100,
        )
    print(f"wrote {OUT.relative_to(ROOT)}: " + ", ".join(f"{v} {k}" for k, v in counts.items()))


if __name__ == "__main__":
    main()
